// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7UsK20DUpi4_3izQaHC3ZdlndFaAn1MA',
    appId: '1:1093226322143:web:5e8bd9b2060d4af726b16a',
    messagingSenderId: '1093226322143',
    projectId: 'fitster-cst9',
    authDomain: 'fitster-cst9.firebaseapp.com',
    storageBucket: 'fitster-cst9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeRjJn5JITbVAuzv-UoCpss9sbY0-MIw',
    appId: '1:1093226322143:android:34fbf70cc552945826b16a',
    messagingSenderId: '1093226322143',
    projectId: 'fitster-cst9',
    storageBucket: 'fitster-cst9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nPC6R5ug5ZcDgIeLBdvgTQsjP-A29Ag',
    appId: '1:1093226322143:ios:d99ff84c5fdb68b426b16a',
    messagingSenderId: '1093226322143',
    projectId: 'fitster-cst9',
    storageBucket: 'fitster-cst9.appspot.com',
    iosBundleId: 'com.example.fitster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nPC6R5ug5ZcDgIeLBdvgTQsjP-A29Ag',
    appId: '1:1093226322143:ios:3053253b2ea4263526b16a',
    messagingSenderId: '1093226322143',
    projectId: 'fitster-cst9',
    storageBucket: 'fitster-cst9.appspot.com',
    iosBundleId: 'com.example.fitster.RunnerTests',
  );
}
